language: php
php:
    - 5.4
    - 5.5
env:
    - P6_TEST_CONFIG=configuration-travis.php
before_script:
    - (cd phprojekt && wget http://getcomposer.org/composer.phar)
    - (cd phprojekt && php composer.phar install --prefer-source --no-interaction --no-progress --dev)
    - mysql -u root -e 'create database `phprojekt-test-memory`'
    - mysql -u root phprojekt-test-memory < phprojekt/tests/test_database_memory.sql

script:
    - phprojekt/vendor/phpunit/phpunit/phpunit.php -c phpunit-travis.xml
